In [1]:
# Naive Bayes using Sklearn - Implementation

In [2]:
import pandas as pd
import numpy as np

In [3]:
golf = pd.read_csv("golf.csv")
golf

Outlook Temperature Humidity  Windy Play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [4]:
# Sklearn cannot work with text data and needs conversion to numeric, hence we have 'lable encoder' in Sklearn

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le1 = LabelEncoder()
golf['Outlook'] = le1.fit_transform(golf['Outlook'])

In [8]:
le2 = LabelEncoder()
golf['Temperature'] = le2.fit_transform(golf['Temperature'])

In [9]:
le3 = LabelEncoder()
golf['Humidity'] = le3.fit_transform(golf['Humidity'])

In [10]:
le4 = LabelEncoder()
golf['Windy'] = le4.fit_transform(golf['Windy'])

In [11]:
le5 = LabelEncoder()
golf['Play'] = le5.fit_transform(golf['Play'])

In [12]:
golf

Outlook  Temperature  Humidity  Windy  Play
0         2            1         0      0     0
1         2            1         0      1     0
2         0            1         0      0     1
3         1            2         0      0     1
4         1            0         1      0     1
5         1            0         1      1     0
6         0            0         1      1     1
7         2            2         0      0     0
8         2            0         1      0     1
9         1            2         1      0     1
10        2            2         1      1     1
11        0            2         0      1     1
12        0            1         1      0     1
13        1            2         0      1     0

In [16]:
X = golf.iloc[:, :-1]
y = golf.iloc[:, -1]

In [13]:
from sklearn.naive_bayes import CategoricalNB

In [14]:
model = CategoricalNB()

In [17]:
model.fit(X, y)

CategoricalNB()

In [18]:
X_test = ["sunny", "hot", "normal", False]

In [19]:
le1.transform(['sunny'])

array([2])

In [21]:
le2.transform(['hot'])

array([1])

In [23]:
le3.transform(['normal'])

array([1])

In [24]:
le4.transform([False])

array([0], dtype=int64)

In [25]:
X_test = np.array([[2,1,1,0]])

In [26]:
model.predict(X_test)

C:\Users\ravin\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([1])

In [27]:
model.predict_proba(X_test)

C:\Users\ravin\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([[0.33508723, 0.66491277]])